[package]
name = "msgflo"
version = "0.0.1"
authors = ["Jon Nordby <jononor@gmail.com>"]

[dependencies]
amqp = "0.0.14"
rustc-serialize = "0.3"
log = "0.3"
argparse = "0.2"
rand = "0.3"

[lib]
name = "msgflo"
path = "src/lib.rs"
