[package]
name = "msgflo"
version = "0.0.3"
authors = ["Jon Nordby <jononor@gmail.com>"]

[dependencies]
amqp = "0.0.16"
rustc-serialize = "0.3"
log = "0.3"
argparse = "0.2"
rand = "0.3"
rumqtt = "0.5"

[lib]
name = "msgflo"
path = "src/lib.rs"
